package auth

import (
	"errors"
	"fmt"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

// Role represents user roles in the system
type Role string

const (
	RoleAdmin    Role = "admin"
	RoleUser     Role = "user"
	RoleProvider Role = "provider"
)

// IsValid checks if the role is a valid role type
func (r Role) IsValid() bool {
	switch r {
	case RoleAdmin, RoleUser, RoleProvider:
		return true
	}
	return false
}

// CanManageAppointments returns true if the role can approve/reject appointments
func (r Role) CanManageAppointments() bool {
	return r == RoleAdmin || r == RoleProvider
}

// Claims represents the JWT claims structure for the appointment service
type Claims struct {
	ProductID uuid.UUID `json:"product_id"`
	UserID    string    `json:"user_id"`
	Role      Role      `json:"role"`
	jwt.RegisteredClaims
}

// Validate checks if the claims are valid
func (c *Claims) Validate() error {
	if c.ProductID == uuid.Nil {
		return errors.New("product_id is required")
	}
	if c.UserID == "" {
		return errors.New("user_id is required")
	}
	if !c.Role.IsValid() {
		return errors.New("invalid role")
	}
	return nil
}

// JWTConfig holds configuration for JWT operations
type JWTConfig struct {
	Secret           string
	Issuer           string
	ExpirationHours  int
	SigningMethod    jwt.SigningMethod
}

// DefaultJWTConfig returns default JWT configuration
func DefaultJWTConfig() JWTConfig {
	return JWTConfig{
		Issuer:          "appointment-service",
		ExpirationHours: 24,
		SigningMethod:   jwt.SigningMethodHS256,
	}
}

// JWTManager handles JWT token operations
type JWTManager struct {
	config JWTConfig
}

// NewJWTManager creates a new JWT manager with the given secret
func NewJWTManager(secret string) *JWTManager {
	config := DefaultJWTConfig()
	config.Secret = secret
	return &JWTManager{config: config}
}

// NewJWTManagerWithConfig creates a new JWT manager with custom configuration
func NewJWTManagerWithConfig(config JWTConfig) *JWTManager {
	return &JWTManager{config: config}
}

// GenerateToken creates a new JWT token with the given claims
// Note: This is primarily for testing. In production, tokens are generated by the main product backend
func (m *JWTManager) GenerateToken(productID uuid.UUID, userID string, role Role) (string, error) {
	now := time.Now()
	
	claims := Claims{
		ProductID: productID,
		UserID:    userID,
		Role:      role,
		RegisteredClaims: jwt.RegisteredClaims{
			Issuer:    m.config.Issuer,
			Subject:   userID,
			IssuedAt:  jwt.NewNumericDate(now),
			ExpiresAt: jwt.NewNumericDate(now.Add(time.Duration(m.config.ExpirationHours) * time.Hour)),
			NotBefore: jwt.NewNumericDate(now),
		},
	}

	token := jwt.NewWithClaims(m.config.SigningMethod, claims)
	return token.SignedString([]byte(m.config.Secret))
}

// GenerateTokenWithExpiry creates a token with custom expiration
func (m *JWTManager) GenerateTokenWithExpiry(productID uuid.UUID, userID string, role Role, expiry time.Time) (string, error) {
	now := time.Now()
	
	claims := Claims{
		ProductID: productID,
		UserID:    userID,
		Role:      role,
		RegisteredClaims: jwt.RegisteredClaims{
			Issuer:    m.config.Issuer,
			Subject:   userID,
			IssuedAt:  jwt.NewNumericDate(now),
			ExpiresAt: jwt.NewNumericDate(expiry),
			NotBefore: jwt.NewNumericDate(now),
		},
	}

	token := jwt.NewWithClaims(m.config.SigningMethod, claims)
	return token.SignedString([]byte(m.config.Secret))
}

// ValidateToken parses and validates a JWT token, returning the claims if valid
func (m *JWTManager) ValidateToken(tokenString string) (*Claims, error) {
	token, err := jwt.ParseWithClaims(tokenString, &Claims{}, func(token *jwt.Token) (interface{}, error) {
		// Validate signing method
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return []byte(m.config.Secret), nil
	})

	if err != nil {
		return nil, m.translateError(err)
	}

	claims, ok := token.Claims.(*Claims)
	if !ok || !token.Valid {
		return nil, ErrInvalidToken
	}

	// Validate custom claims
	if err := claims.Validate(); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidClaims, err)
	}

	return claims, nil
}

// translateError converts jwt-go errors to our custom errors
func (m *JWTManager) translateError(err error) error {
	switch {
	case errors.Is(err, jwt.ErrTokenMalformed):
		return ErrMalformedToken
	case errors.Is(err, jwt.ErrTokenSignatureInvalid):
		return ErrInvalidSignature
	case errors.Is(err, jwt.ErrTokenExpired):
		return ErrExpiredToken
	case errors.Is(err, jwt.ErrTokenNotValidYet):
		return ErrTokenNotValidYet
	default:
		return fmt.Errorf("%w: %v", ErrInvalidToken, err)
	}
}

// Custom errors for JWT operations
var (
	ErrInvalidToken     = errors.New("invalid token")
	ErrMalformedToken   = errors.New("malformed token")
	ErrExpiredToken     = errors.New("token has expired")
	ErrInvalidSignature = errors.New("invalid token signature")
	ErrTokenNotValidYet = errors.New("token not valid yet")
	ErrInvalidClaims    = errors.New("invalid token claims")
	ErrMissingToken     = errors.New("missing authorization token")
)

// IsExpiredError checks if the error is due to token expiration
func IsExpiredError(err error) bool {
	return errors.Is(err, ErrExpiredToken)
}

// IsInvalidError checks if the error is due to invalid token
func IsInvalidError(err error) bool {
	return errors.Is(err, ErrInvalidToken) ||
		errors.Is(err, ErrMalformedToken) ||
		errors.Is(err, ErrInvalidSignature) ||
		errors.Is(err, ErrInvalidClaims)
}
